apiVersion: v2
kind: ConfigMap
metadata:
  name: web-content
  labels:
    app: web
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head><title>ArgoCD Lab</title></head>
      <body>
        <h1>Hello from ArgoCD lab</h1>
        <p>Version: v1</p>
      </body>
    </html>
